const assert = require('node:assert/strict');
const { test } = require('node:test');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const file = path.resolve('src/components/freeze-hold-print-report.tsx');
const compiled = new Module(file, module);
compiled.filename = file;
compiled.paths = Module._nodeModulePaths(path.dirname(file));
compiled._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true },
}).outputText, file);
const { FreezeHoldPrintDocument } = compiled.exports;
// Fixtures are test-only; the production report receives the existing package object.
const address = `0x${'a'.repeat(40)}`, destination = `0x${'b'.repeat(40)}`;
const hash = `0x${'c'.repeat(64)}`;
const data = {
  requestId: 'request-print-regression', generatedAt: '2026-09-21T12:34:56Z', status: 'DRAFT',
  requestedIntervention: 'Temporary Hold Review', priority: 'High', targetEntity: 'Analyst-entered target', targetEntitySource: 'Unverified',
  case: { id: 'case-id', code: 'CT-PRINT', title: 'Evidence print regression', description: '' }, network: 'Ethereum Mainnet',
  reportedSuspectWallets: [address],
  blockchainObservedFacts: { valueUnit: 'wei', transactions: [{ hash, from: address, to: destination, value: '123456789', timestamp: null, status: 'unknown', blockNumber: '123' }] },
  custodialEndpoints: [], analyticalSignals: [], crossWalletEvidence: null, monitoringAlerts: [],
  reason: '<script>alert("unsafe")</script>', analystNotes: 'Current investigator notes',
  evidenceReadiness: { percent: 50, criteria: { 'Case reference': true, 'Attribution': false }, meaning: 'Availability only.' },
  auditTrail: [{ status: 'DRAFT', at: '2026-09-21T12:34:56Z', note: 'Created internally' }], delivery: 'No external delivery.', limitations: ['Partial sample.'], notices: [],
};
const render = packageData => renderToStaticMarkup(React.createElement(FreezeHoldPrintDocument, { data: packageData }));
test('print document contains full loaded evidence, fields, notices, and escaped analyst text', () => {
  const html = render(data);
  for (const expected of [data.requestId, data.case.code, address, destination, hash, '123456789', 'unknown', 'Current investigator notes', 'Evidence Readiness', 'NOT probability of fraud', 'No verified custodial attribution is currently available.', 'CHAINTRACE does not autonomously freeze blockchain assets.', 'Generated by CHAINTRACE — NODEHIVE']) assert.ok(html.includes(expected), expected);
  assert.ok(!html.includes('<script>'));
  assert.ok(html.includes('&lt;script&gt;'));
  assert.ok(!html.includes('<pre'));
  assert.ok(html.includes('Unavailable / not provided'));
  const updated = render({ ...data, analystNotes: 'Updated current notes', status: 'READY FOR REVIEW' });
  assert.ok(updated.includes('Updated current notes'));
  assert.ok(updated.includes('READY FOR REVIEW'));
});
test('large packages retain the final transaction and use unclipped normal print flow', () => {
  const transactions = Array.from({ length: 120 }, (_, i) => ({ ...data.blockchainObservedFacts.transactions[0], hash: `0x${i.toString(16).padStart(64, '0')}` }));
  const html = render({ ...data, blockchainObservedFacts: { ...data.blockchainObservedFacts, transactions } });
  assert.ok(html.includes(transactions[119].hash));
  assert.ok(html.includes('Transaction 120'));
  assert.ok(html.includes('position: static !important'));
  assert.ok(html.includes('overflow-wrap: anywhere'));
  assert.ok(html.includes('body:has(#freeze-hold-print-report) &gt;') || html.includes('body:has(#freeze-hold-print-report) >'));
  const page = fs.readFileSync('src/app/(dashboard)/freeze-hold/page.tsx', 'utf8');
  assert.ok(!page.includes('visibility: hidden'));
  assert.ok(page.includes('<FreezeHoldPrintReport data={packageData} />'));
  assert.ok(page.includes('JSON.stringify({ ...packageData, auditTrail: [...audit, entry] }, null, 2)'));
});
test('screen and print share twelve report sections and full evidence without a JSON preview', () => {
  const print = render(data);
  const screen = renderToStaticMarkup(React.createElement(FreezeHoldPrintDocument, { data, printable: false }));
  for (const heading of ['Request Summary', 'Case Information', 'Reported / Suspect Wallets', 'Blockchain Evidence', 'Money Fingerprint', 'Fund Splitting', 'Cross-Wallet Intelligence', 'Custodial Endpoint Intelligence', 'Monitoring / Alert Evidence', 'Evidence Readiness', 'Authorized Intervention', 'Important Findings / Limitations']) {
    assert.ok(print.includes(heading), heading);
    assert.ok(screen.includes(heading), heading);
  }
  for (const value of [address, destination, hash, data.requestId, '123456789', 'Current investigator notes', 'No blockchain evidence is currently available for this field.']) {
    assert.ok(print.includes(value), value);
    assert.ok(screen.includes(value), value);
  }
  assert.ok(screen.includes('Copy address'));
  assert.ok(!print.includes('Copy address'));
  assert.ok(!screen.includes('<pre'));
  const page = fs.readFileSync('src/app/(dashboard)/freeze-hold/page.tsx', 'utf8');
  assert.ok(page.includes('<FreezeHoldEvidenceReport data={packageData} />'));
  assert.ok(!page.includes('<pre'));
  assert.ok(page.includes('Download JSON'));
});

test('prepared reports retain distinct internal status and manually recorded external responses', () => {
  const html = render({ ...data, status: 'PREPARED FOR AUTHORIZED ESCALATION', preparedAt: '2026-09-21T12:35:00Z', targetDetails: { entityType: 'Custodian', attributionStatus: 'UNVERIFIED / MANUAL ENTRY', contactReference: 'Target ref', attributionReference: '' }, evidenceValidation: [{ label: 'Transaction evidence', required: false, state: 'MISSING', explanation: 'Not loaded' }], externalResponses: [{ status: 'ACKNOWLEDGED', referenceId: 'EXT-123', entity: 'Recorded responder', respondedAt: '2026-09-21T12:36:00Z', recordedAt: '2026-09-21T12:37:00Z', confirmed: true, notes: 'Received outside the app', source: 'Analyst recorded' }] });
  for (const value of ['PREPARED FOR AUTHORIZED ESCALATION', 'External Response Status', 'ACKNOWLEDGED', 'EXT-123', 'Recorded responder', 'not independently verified by CHAINTRACE', 'MISSING', 'Target ref']) assert.ok(html.includes(value), value);
  assert.ok(render(data).includes('No external response recorded.'));
});
