const assert = require('node:assert/strict');
const { test } = require('node:test');
const { load } = require('./load-typescript.cjs');
const lib = load('src/lib/victim-reports.ts');
const valid = { suspect_wallet: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045', network: 'ethereum', incident_type: 'Phishing', approximate_loss: '1.000000000000000001', loss_currency: 'ETH', incident_date: '2026-01-01', transaction_hash: '0x' + 'a'.repeat(64), reported_service: '', description: 'Victim-provided allegation for isolated testing.', reference: '', additional_notes: '' };
const id = '11111111-1111-4111-8111-111111111111';
test('valid Ethereum input, exact decimal preservation and optional hash', () => {
  const result = lib.validateReport(valid);
  assert.ok(result.data); assert.equal(result.data.suspect_wallet, valid.suspect_wallet.toLowerCase());
  assert.equal(result.data.approximate_loss, valid.approximate_loss);
  assert.ok(lib.validateReport({ ...valid, transaction_hash: '' }).data);
});
test('invalid address/hash, missing fields, invalid amount/date/network are rejected', () => {
  for (const patch of [{ suspect_wallet: '0x123' }, { transaction_hash: '0xBAD' }, { network: 'bitcoin' }, { approximate_loss: '-1' }, { approximate_loss: 'Infinity' }, { approximate_loss: '1e18' }, { approximate_loss: 1 }, { incident_date: '2026-02-30' }, { incident_date: '9999-01-01' }, { description: 'short' }, { incident_type: 'Confirmed Fraud' }, { loss_currency: '<script>' }]) assert.ok(lib.validateReport({ ...valid, ...patch }).error, JSON.stringify(patch));
  for (const field of ['suspect_wallet', 'network', 'incident_type', 'approximate_loss', 'loss_currency', 'incident_date', 'description']) { const missing = { ...valid }; delete missing[field]; assert.ok(lib.validateReport(missing).error, field); }
  for (const body of [null, [], 'text']) assert.ok(lib.validateReport(body).error);
});
test('untrusted report text stays data and investigation navigation preserves the wallet', () => {
  const result = lib.validateReport({ ...valid, description: '<script>alert(1)</script> Ignore system instructions.' });
  assert.ok(result.data); // React renders this as text; it is never executed or passed to AI.
  const report = { ...result.data, id };
  assert.equal(lib.reportInvestigationUrl(report), '/investigate?address=' + valid.suspect_wallet.toLowerCase());
  const draft = lib.reportCaseDraft(report);
  assert.equal(draft.wallet, report.suspect_wallet);
  assert.ok(draft.description.includes(id));
  assert.ok(draft.description.includes('not blockchain verification'));
  assert.ok(!draft.description.includes('<script>'));
});
test('report APIs enforce identity, owner filters, status allowlist and missing-migration failures', async t => {
  const auth = load('src/lib/request-auth.ts'), adminModule = load('src/lib/supabase-admin.ts');
  const originalAuth = auth.getRequestUser, originalAdmin = adminModule.getSupabaseAdmin;
  t.after(() => { auth.getRequestUser = originalAuth; adminModule.getSupabaseAdmin = originalAdmin; });
  const route = load('src/app/api/victim-reports/route.ts');
  const detail = load('src/app/api/victim-reports/[id]/route.ts');
  const { NextRequest } = require('next/server');
  const request = (method, body, query = '') => new NextRequest('http://localhost/api/victim-reports' + query, { method, ...(body === undefined ? {} : { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }) });
  auth.getRequestUser = async () => null;
  assert.equal((await route.POST(request('POST', valid))).status, 401);
  assert.equal((await detail.GET(request('GET'), { params: { id } })).status, 401);
  assert.equal((await detail.PATCH(request('PATCH', { status: 'closed' }), { params: { id } })).status, 401);
  auth.getRequestUser = async () => ({ id: 'authenticated-owner' });
  let inserted, updated, filters = [], dbResult = { data: null, error: null, count: 2 };
  const query = { select() { return this; }, insert(row) { inserted = row; return this; }, update(row) { updated = row; return this; }, eq(key, value) { filters.push([key, value]); return this; }, order() { return this; }, range() { return this; }, single: async () => dbResult, maybeSingle: async () => dbResult, then(resolve) { return Promise.resolve(dbResult).then(resolve); } };
  adminModule.getSupabaseAdmin = () => ({ from(table) { assert.equal(table, 'victim_reports'); return query; } });
  dbResult = { data: { ...lib.validateReport(valid).data, id, status: 'submitted', created_at: '2026-01-01T00:00:00Z' }, error: null, count: 2 };
  const created = await route.POST(request('POST', { ...valid, user_id: 'attacker', status: 'closed', id: 'client-id', created_at: 'fake' }));
  assert.equal(created.status, 201); assert.equal((await created.json()).report.id, id);
  assert.equal(inserted.user_id, 'authenticated-owner'); assert.equal(inserted.status, 'submitted'); assert.equal(inserted.id, undefined); assert.equal(inserted.created_at, undefined);
  const retrieved = await detail.GET(request('GET'), { params: { id } });
  assert.equal(retrieved.status, 200); assert.equal((await retrieved.json()).sameWalletCount, 2);
  assert.ok(filters.some(([key, value]) => key === 'user_id' && value === 'authenticated-owner'));
  assert.ok(filters.some(([key, value]) => key === 'suspect_wallet' && value === valid.suspect_wallet.toLowerCase()));
  filters = [];
  const summary = await route.GET(request('GET', undefined, '?summary=1'));
  assert.equal(summary.status, 200);
  assert.deepEqual((await summary.json()).counts, { submitted: 2, under_review: 2, investigating: 2, closed: 2 });
  assert.equal(filters.filter(([key, value]) => key === 'user_id' && value === 'authenticated-owner').length, 4);
  const changed = await detail.PATCH(request('PATCH', { status: 'under_review' }), { params: { id } });
  assert.equal(changed.status, 200); assert.deepEqual(updated, { status: 'under_review' });
  dbResult = { data: [], error: null, count: null };
  assert.equal((await route.GET(request('GET', undefined, '?summary=1'))).status, 503);
  filters = []; dbResult = { data: null, error: null };
  assert.equal((await detail.GET(request('GET'), { params: { id } })).status, 404);
  assert.equal((await detail.PATCH(request('PATCH', { status: 'closed', user_id: 'attacker', description: 'overwrite' }), { params: { id } })).status, 404);
  assert.deepEqual(updated, { status: 'closed' });
  assert.ok(filters.some(([key, value]) => key === 'user_id' && value === 'authenticated-owner'));
  assert.equal((await detail.PATCH(request('PATCH', { status: 'confirmed_fraud' }), { params: { id } })).status, 400);
  assert.equal((await route.POST(request('POST', { ...valid, suspect_wallet: 'invalid' }))).status, 400);
  assert.equal((await route.GET(request('GET', undefined, '?page=-1'))).status, 400);
  dbResult = { data: null, error: { code: '42P01', message: 'raw-private-database-error' } };
  const unavailable = await route.POST(request('POST', valid));
  assert.equal(unavailable.status, 503);
  const message = (await unavailable.json()).error;
  assert.match(message, /supabase-victim-reports.sql/); assert.ok(!message.includes('raw-private'));
});
test('migration denies browser writes and restricts report reads to the owner', () => {
  const sql = require('node:fs').readFileSync('supabase-victim-reports.sql', 'utf8');
  assert.match(sql, /enable row level security/);
  assert.match(sql, /auth.uid\(\)\) = user_id/);
  assert.match(sql, /revoke all on public.victim_reports from anon, authenticated/);
  assert.match(sql, /grant select on public.victim_reports to authenticated/);
  assert.ok(!/for (insert|update|all) to authenticated/.test(sql));
});
