'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { authenticatedFetch } from '@/lib/client-api';
import { alertInvestigationUrl, type AlertDetail } from '@/lib/alerts';
import { formatEth } from '@/lib/wallet-analysis';
import { WalletAddress } from '@/components/wallet-address';

const time = (value: string | null) => value ? new Date(value).toISOString().replace('T', ' ').replace('.000Z', ' UTC') : 'Unavailable';
const amount = (value: string | null) => value === null ? 'Unavailable' : formatEth(BigInt(value));
export function AlertEvidence({ id }: { id: string }) {
  const [detail, setDetail] = useState<AlertDetail | null>(null), [error, setError] = useState(''), [version, setVersion] = useState(0);
  useEffect(() => { let active = true; setError(''); setDetail(null); authenticatedFetch(`/api/alerts/${id}`).then(response => response.json()).then(data => { if (!data.alert || !data.evidence) throw new Error(); if (active) setDetail(data); }).catch(() => { if (active) setError('Unable to load authorized alert evidence. Please retry.'); }); return () => { active = false; }; }, [id, version]);
  if (error) return <div role="alert" className="mt-5 text-sm text-red-200">{error}<button className="button-secondary ml-3" onClick={() => setVersion(value => value + 1)}>Retry details</button></div>;
  if (!detail) return <p role="status" className="mt-5 text-sm text-slate-400">Loading stored evidence…</p>;
  const { alert, evidence, transaction, monitor } = detail;
  const investigation = alert.wallet ? alertInvestigationUrl(alert.wallet) : null;
  return <div className="mt-5 space-y-5 border-t border-slate-800 pt-5">
    <section><h3 className="text-sm font-semibold text-white">Observed Evidence</h3><p className="mt-2 text-xs text-slate-400">Source: your stored monitor_alerts, monitor_transactions and wallet_monitors records. No blockchain request is made when opening this panel.</p><dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Entry label="Detection time">{time(alert.created_at)}</Entry><Entry label="Transaction time">{time(transaction?.timestamp || null)}</Entry><Entry label="Observed trigger amount">{amount(transaction?.valueWei ?? null)}</Entry><Entry label="Stored transaction status">{transaction?.status || 'Unavailable'}</Entry><Entry label="Source address">{transaction?.from ? <WalletAddress address={transaction.from} /> : 'Unavailable'}</Entry><Entry label="Destination address">{transaction?.to ? <WalletAddress address={transaction.to} /> : 'Unavailable / no recipient'}</Entry><Entry label="Latest monitoring check">{time(monitor.lastCheck)}</Entry><Entry label="Latest successful check">{time(monitor.lastSuccess)}</Entry><Entry label="Monitor state">{monitor.active === null ? 'Unavailable' : monitor.active ? 'Active' : 'Paused'}</Entry></dl>{!transaction && <p className="mt-3 text-xs text-amber-100">{detail.transactionUnavailable ? 'Stored transaction evidence could not be retrieved. The alert remains available.' : 'No matching valid stored transaction was available for this alert.'}</p>}</section>
    <section><h3 className="text-sm font-semibold text-white">Analytical Signal / Reason for Alert</h3><p className="mt-2 text-sm leading-6 text-slate-300">{alert.description}</p><p className="mt-2 text-xs text-slate-500">Stored title: {alert.title}. Stored priority: {alert.severity}. Priority is not a fraud determination.</p>{alert.risk_score !== null && <p className="mt-2 text-xs text-slate-400">Stored analytical score: {alert.risk_score}. This is not a probability of fraud.</p>}
      {alert.alert_type === 'fund_splitting' && <><p className="mt-3 text-xs leading-6 text-slate-400">Current monitoring rule: successful positive-value outgoing transfers reach at least three distinct destinations within 24 hours, with a newly stored triggering transaction. The rule flags distribution for review; it does not infer intent.</p><dl className="mt-3 grid gap-3 sm:grid-cols-2"><Entry label="Stored destination count">{evidence.destinationCount ?? 'Unavailable'}</Entry><Entry label="Observed window total">{amount(evidence.totalWei)}</Entry><Entry label="Window start">{time(evidence.windowStart)}</Entry><Entry label="Window end">{time(evidence.windowEnd)}</Entry></dl></>}
      {alert.alert_type === 'unusual_movement' && <><p className="mt-3 text-xs leading-6 text-slate-400">Current monitoring rule: a newly stored successful outgoing transfer is at least four times the average of the other recent successful transactions, with at least three baseline transactions and a positive baseline average. The baseline includes successful activity in all directions, not just outgoing transfers.</p><dl className="mt-3 grid gap-3 sm:grid-cols-2"><Entry label="Stored baseline average">{amount(evidence.baselineAverageWei)}</Entry><Entry label="Stored threshold multiplier">{evidence.multiplier === null ? 'Unavailable' : `${evidence.multiplier}×`}</Entry></dl></>}
    </section>
    <section><h3 className="text-sm font-semibold text-white">Related Transactions</h3><div className="mt-3 flex flex-wrap gap-3">{[...new Set([...(alert.source_transaction_hash ? [alert.source_transaction_hash] : []), ...evidence.hashes])].map(hash => <a key={hash} href={`https://etherscan.io/tx/${hash}`} target="_blank" rel="noreferrer" title={hash} className="font-mono text-xs text-cyan-200">{hash.slice(0, 10)}…{hash.slice(-8)} ↗</a>)}</div>{!alert.source_transaction_hash && !evidence.hashes.length && <p className="mt-2 text-xs text-slate-400">No valid transaction reference available.</p>}</section>
    <section className="rounded-xl border border-amber-400/20 p-4 text-xs leading-6 text-amber-100"><h3 className="font-semibold">Limitations</h3><p>Stored detections are historical snapshots of bounded recent Ethereum activity, not complete wallet history. A later investigation may retrieve a different sample. Polling delays and provider availability affect coverage. Missing or malformed fields are unavailable, never inferred. Displayed ETH amounts are rounded/truncated by the existing six-decimal formatter. Current rule descriptions are not a versioned audit of historical rules. No ownership, service identity or criminal intent is established.</p></section>
    {investigation && <><nav aria-label="Continue alert investigation" className="flex flex-wrap gap-3"><Link className="button-secondary" href={investigation}>Investigate Wallet</Link><Link className="button-secondary" href={`${investigation}#money-fingerprint`}>Money Fingerprint</Link><Link className="button-secondary" href={`${investigation}#fund-splitting`}>Fund Splitting Alarm</Link><Link className="button-secondary" href={`/blockchain-intelligence?query=${encodeURIComponent(alert.wallet!)}`}>Blockchain Intelligence</Link>{alert.source_transaction_hash && <Link className="button-secondary" href={`/blockchain-intelligence?query=${encodeURIComponent(alert.source_transaction_hash)}`}>Inspect Transaction</Link>}</nav><p className="text-xs text-slate-500">These actions prefill the existing investigation tools. Run the search/analysis there to retrieve current provider evidence.</p><AlertCaseAction wallet={alert.wallet!} /></>}
  </div>;
}
function Entry({ label, children }: { label: string; children: React.ReactNode }) { return <div className="min-w-0"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm text-slate-200">{children}</dd></div>; }
type CaseOption = { id: string; title: string; case_code: string; wallets: { address: string }[] };
function AlertCaseAction({ wallet }: { wallet: string }) {
  const [cases, setCases] = useState<CaseOption[] | null>(null), [selected, setSelected] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [saved, setSaved] = useState('');
  async function load() { setBusy(true); setError(''); try { const response = await authenticatedFetch('/api/cases'); const data = await response.json(); if (!Array.isArray(data.cases)) throw new Error(); setCases(data.cases); } catch { setError('Unable to load your cases.'); } finally { setBusy(false); } }
  async function add() {
    if (!selected || busy) return; setBusy(true); setError(''); setSaved('');
    try { const response = await authenticatedFetch(`/api/cases/${encodeURIComponent(selected)}/wallets`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ address: wallet }) }); const data = await response.json(); if (data.wallet?.address?.toLowerCase() !== wallet.toLowerCase()) throw new Error('Wallet addition was not confirmed.'); setSaved(selected); setCases(items => items?.map(item => item.id === selected ? { ...item, wallets: [...item.wallets, { address: wallet }] } : item) || []); }
    catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to add wallet to case.'); }
    finally { setBusy(false); }
  }
  const contains = (item: CaseOption) => item.wallets.some(entry => entry.address.toLowerCase() === wallet.toLowerCase());
  return <section className="rounded-xl border border-slate-800 p-4"><h3 className="text-sm font-semibold text-white">Case workflow</h3><p className="mt-2 text-xs text-slate-400">Add the monitored wallet to one of your cases using the existing case workflow. This does not attach the alert itself or imply a case association.</p>{cases === null ? <button className="button-secondary mt-3" disabled={busy} onClick={() => void load()}>{busy ? 'Loading cases…' : 'Choose a case'}</button> : <><div className="mt-3 flex flex-wrap gap-3"><label className="text-xs text-slate-400">Your case<select className="field mt-2 max-w-full" value={selected} disabled={busy} onChange={event => setSelected(event.target.value)}><option value="">Select a case</option>{cases.filter(item => !contains(item)).map(item => <option key={item.id} value={item.id}>{item.case_code} · {item.title}</option>)}</select></label><button className="button-secondary self-end" disabled={busy || !cases.some(item => item.id === selected && !contains(item))} onClick={() => void add()}>{busy ? 'Saving…' : 'Add wallet to case'}</button></div>{!cases.length && <Link href="/cases" className="mt-3 block text-xs text-cyan-200">Create a case in Cases</Link>}<div className="mt-3 flex flex-wrap gap-3">{cases.filter(contains).map(item => <Link key={item.id} href={`/cases/${item.id}`} className="text-xs text-cyan-200">Open {item.case_code} · contains this wallet</Link>)}</div></>}{saved && <p role="status" className="mt-3 text-xs text-cyan-200">Wallet added to the selected case. The alert record was not changed.</p>}{error && <p role="alert" className="mt-3 text-xs text-red-200">{error}</p>}</section>;
}
