'use client';
import Link from 'next/link';
import { TransactionLink } from '@/components/transaction-link';
import { useState } from 'react';
import { WalletAddress } from '@/components/wallet-address';
import { formatEth } from '@/lib/wallet-analysis';
import type { FundFlowGraph } from '@/lib/fund-flow';

const short = (value: string) => value.slice(0, 8) + '...' + value.slice(-6);
function Fact({ label, children }: { label: string; children: React.ReactNode }) { return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 break-words text-sm text-slate-200">{children}</dd></div>; }
export function FundFlowCanvas({ graph, caseId }: { graph: FundFlowGraph; caseId: string }) {
  const [selection, setSelection] = useState('');
  const columns = [graph.nodes.filter(node => !node.reported && !graph.edges.some(edge => edge.to === node.address && graph.nodes.some(source => source.address === edge.from && source.reported))), graph.nodes.filter(node => node.reported), graph.nodes.filter(node => !node.reported && graph.edges.some(edge => edge.to === node.address && graph.nodes.some(source => source.address === edge.from && source.reported)))];
  const height = Math.max(430, Math.max(...columns.map(column => column.length)) * 110 + 100);
  const positions = new Map(columns.flatMap((column, index) => column.map((node, row) => [node.address, { x: 170 + index * 380, y: 85 + row * 110 }] as const)));
  const node = graph.nodes.find(item => 'node:' + item.address === selection);
  const edge = graph.edges.find(item => 'edge:' + item.id === selection);
  if (!graph.nodes.length) return <div className="panel p-10 text-center"><h2 className="text-lg font-semibold text-white">No fund-flow paths to display</h2><p className="mt-3 text-sm text-slate-400">Load case evidence or adjust the filters. No successful, valid nonzero transfers match the current view. No synthetic connections are added.</p></div>;
  return <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
    <section className="panel min-w-0 p-4"><h2 className="text-lg font-semibold text-white">Observed Fund Flow</h2><p className="mt-2 text-xs text-slate-400">Select a node or arrow. Use Tab and Enter for keyboard access, or the evidence selector below. Scroll to explore the bounded graph.</p>
      <label className="mt-4 block text-xs">Select graph evidence<select className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm" value={node || edge ? selection : ''} onChange={event => setSelection(event.target.value)}><option value="">Choose a node or transfer group</option><optgroup label="Wallet nodes">{graph.nodes.map(item => <option key={item.address} value={'node:' + item.address}>{item.reported ? 'Reported' : 'Connected'}: {item.address}</option>)}</optgroup><optgroup label="Observed transfer groups">{graph.edges.map(item => <option key={item.id} value={'edge:' + item.id}>{short(item.from)} → {short(item.to)} ({item.transactions.length} transfers)</option>)}</optgroup></select></label>
      <div className="mt-4 max-h-[660px] overflow-auto rounded-xl border border-slate-800 bg-slate-950/70" tabIndex={0} aria-label="Scrollable fund-flow graph">
        <svg viewBox={`0 0 1100 ${height}`} style={{ width: '100%', minWidth: 850, height: 'auto' }} role="group" aria-label="Directed observed Ethereum fund-flow graph">
          <defs><marker id="flow-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#94a3b8" /></marker></defs>
          {['Incoming counterparties', 'Reported / case wallets', 'Observed destinations'].map((title, index) => <text key={title} x={170 + index * 380} y={25} textAnchor="middle" fill="#94a3b8" fontSize="12">{title}</text>)}
          {graph.edges.map(item => {
            const from = positions.get(item.from)!, to = positions.get(item.to)!;
            const direction = from.x <= to.x ? 1 : -1;
            const x1 = from.x + 96 * direction, x2 = to.x - 104 * direction;
            const path = item.from === item.to ? `M ${from.x + 80} ${from.y - 30} C ${from.x + 170} ${from.y - 95}, ${from.x + 190} ${from.y + 80}, ${from.x + 92} ${from.y + 20}` : from.x === to.x ? `M ${from.x + 96} ${from.y} C ${from.x + 200} ${from.y}, ${to.x + 200} ${to.y}, ${to.x + 104} ${to.y}` : `M ${x1} ${from.y} C ${(x1 + x2) / 2} ${from.y + 22 * direction}, ${(x1 + x2) / 2} ${to.y + 22 * direction}, ${x2} ${to.y}`;
            const active = edge?.id === item.id;
            return <g key={item.id} role="button" tabIndex={0} aria-label={`${item.transactions.length} observed transfers from ${item.from} to ${item.to}`} onClick={() => setSelection('edge:' + item.id)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelection('edge:' + item.id); } }} className="cursor-pointer outline-none focus:opacity-60 hover:opacity-70"><title>{item.transactions.length} observed transfers; {item.totalWei.toString()} wei</title><path d={path} fill="none" stroke="transparent" strokeWidth={18} /><path d={path} fill="none" stroke={active ? '#22d3ee' : item.splitting ? '#fbbf24' : '#64748b'} strokeWidth={active ? 3 : 1.8} strokeDasharray={item.splitting ? '6 3' : undefined} markerEnd="url(#flow-arrow)" />{from.x !== to.x && <text x={(x1 + x2) / 2} y={(from.y + to.y) / 2 - 8} fill="#cbd5e1" fontSize="10" textAnchor="middle" paintOrder="stroke" stroke="#020617" strokeWidth="3">{item.transactions.length} tx</text>}</g>;
          })}
          {graph.nodes.map(item => {
            const point = positions.get(item.address)!;
            const color = item.attribution.status === 'VERIFIED' ? '#6ee7b7' : item.analysis?.splittingAlarm ? '#fbbf24' : item.reported ? '#22d3ee' : '#94a3b8';
            return <g key={item.address} transform={`translate(${point.x},${point.y})`} role="button" tabIndex={0} aria-label={`Inspect ${item.reported ? 'reported wallet' : 'connected wallet'} ${item.address}`} onClick={() => setSelection('node:' + item.address)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelection('node:' + item.address); } }} className="cursor-pointer outline-none focus:opacity-60 hover:opacity-80"><title>{item.address}</title><rect x={-96} y={-34} width={192} height={72} rx={12} fill={node?.address === item.address ? '#164e63' : '#0f172a'} stroke={color} strokeWidth={node?.address === item.address ? 3 : 1.5} /><text textAnchor="middle" y={-15} fill={color} fontSize="9">{item.attribution.status === 'VERIFIED' ? 'VERIFIED CUSTODIAL ENDPOINT' : item.reported ? 'REPORTED / CASE WALLET' : 'CONNECTED - UNKNOWN'}</text><text textAnchor="middle" y={3} fill="#f1f5f9" fontSize="12" fontFamily="monospace">{short(item.address)}</text><text textAnchor="middle" y={23} fill={color} fontSize="9">{item.analysis?.splittingAlarm ? 'FUND SPLITTING SIGNAL' : item.repeated ? 'REPEATED DESTINATION' : 'OBSERVED CONNECTION'}</text></g>;
          })}
        </svg>
      </div>
      <ul className="mt-4 flex flex-wrap gap-3 text-xs" aria-label="Graph legend"><li className="text-cyan-200">● Reported Wallet</li><li className="text-slate-300">● Connected Wallet / Unknown / Unattributed</li><li className="text-amber-200">● Fund Splitting Signal (dashed paths)</li><li className="text-emerald-200">● Verified Custodial Endpoint</li></ul><p className="mt-3 text-xs text-slate-400">Positions are layout choices, not evidence of ownership, chronology, or fraud. All edges follow observed sender → recipient direction; nodes may send and receive.</p>
    </section>
    <aside className="panel space-y-4 p-5" aria-live="polite"><h2 className="text-lg font-semibold text-white">Evidence Inspector</h2>{!node && !edge && <p className="text-sm text-slate-400">Select an observed wallet or transfer group.</p>}
      {node && <><p className="text-xs text-cyan-200">OBSERVED BLOCKCHAIN FACT</p><p className="break-all font-mono text-xs">{node.address}</p><WalletAddress address={node.address} /><dl className="space-y-3"><Fact label="Role">{node.reported ? 'Reported / suspect case wallet; not a fraud determination' : 'Connected counterparty'}</Fact><Fact label="Network">Ethereum Mainnet</Fact><Fact label="Incoming / outgoing transactions">{node.incomingCount} / {node.outgoingCount}</Fact><Fact label="Observed incoming / outgoing value">{formatEth(node.incomingWei)} / {formatEth(node.outgoingWei)}</Fact><Fact label="Exact incoming / outgoing wei">{node.incomingWei.toString()} / {node.outgoingWei.toString()}</Fact><Fact label="First / latest observed activity">{node.first || 'Unavailable'} / {node.latest || 'Unavailable'}</Fact><Fact label="Repeated destination">{node.repeated ? 'Received more than one observed transfer from case wallets' : 'Not observed in the loaded sample'}</Fact><Fact label="Connected case wallets">{node.connectedCaseWallets.length ? node.connectedCaseWallets.map(address => <p className="break-all" key={address}>{address}</p>) : 'None observed'}</Fact></dl><p className="text-xs text-slate-400">Inspector totals cover all eligible retrieved transfers, before display filters. Counterparty history beyond the loaded case evidence is not known.</p>
        {node.analysis && <div className="space-y-3 border-t border-slate-700 pt-4"><p className="text-xs text-amber-200">ANALYTICAL SIGNAL</p><h3 className="font-semibold text-white">Money Fingerprint</h3><p className="text-sm">{node.analysis.counterparties.length} counterparties; average {formatEth(node.analysis.averageTransactionWei)}; {node.analysis.frequency.transactionsPerDay?.toFixed(2) || 'Unavailable'} transfers/day.</p>{node.analysis.risk.signals.map(signal => <p className="text-xs" key={signal}>{signal}</p>)}{node.analysis.splittingAlarm ? <><h3 className="text-sm font-semibold text-amber-200">FUND SPLITTING SIGNAL</h3><p className="text-xs">{node.analysis.splittingAlarm.transactionCount} transactions to {node.analysis.splittingAlarm.destinationCount} destinations from {node.analysis.splittingAlarm.start} to {node.analysis.splittingAlarm.end}. {formatEth(node.analysis.splittingAlarm.totalWei)}</p><p className="text-xs">Supporting hashes (some paths may be hidden by filters):</p>{node.analysis.splittingAlarm.transactionHashes.map(hash => <p className="break-all font-mono text-xs" key={hash}><TransactionLink hash={hash} caseId={caseId} /></p>)}</> : <p className="text-xs">No Fund Splitting finding in this retrieved sample.</p>}<p className="text-xs text-amber-200">Fund splitting is an analytical signal based on observed transaction behavior and is not proof of fraud.</p></div>}
        <div className="space-y-2 border-t border-slate-700 pt-4"><h3 className="text-xs font-semibold text-emerald-200">{node.attribution.status === 'VERIFIED' ? 'VERIFIED ATTRIBUTION' : 'UNATTRIBUTED / UNKNOWN'}</h3><p className="text-xs">{node.attribution.attribution}</p>{node.attribution.record && <dl className="space-y-2"><Fact label="Entity">{node.attribution.record.entityName} ({node.attribution.record.entityType})</Fact><Fact label="Source">{node.attribution.record.sourceName}</Fact><Fact label="Reference">{node.attribution.record.sourceReference || 'Unavailable'}</Fact><Fact label="Verified at">{node.attribution.record.verifiedAt}</Fact></dl>}<p className="text-xs">Attribution is not proof of fraud or authority to freeze assets.</p></div>
        <Link className="block rounded-xl border border-cyan-400/25 p-3 text-sm text-cyan-200" href={`/freeze-hold?case=${encodeURIComponent(caseId)}&wallet=${encodeURIComponent(node.address)}`}>Open in Freeze/Hold Intelligence</Link><p className="text-xs text-slate-400">Opens a preparation workflow. Does not freeze funds or submit an external request.</p>
      </>}
      {edge && <><p className="text-xs text-cyan-200">OBSERVED BLOCKCHAIN FACT</p><dl className="space-y-3"><Fact label="Source address">{edge.from}</Fact><Fact label="Destination address">{edge.to}</Fact><Fact label="Direction">Observed sender → recipient</Fact><Fact label="Network">Ethereum Mainnet</Fact><Fact label="Displayed aggregate">{edge.transactions.length} transactions; {formatEth(edge.totalWei)} ({edge.totalWei.toString()} wei)</Fact></dl>{edge.splitting && <p className="text-xs text-amber-200">This group includes existing Fund Splitting evidence. Not proof of fraud.</p>}<h3 className="text-sm font-semibold text-white">Individual observed transactions</h3>{edge.transactions.map(tx => <div key={tx.hash} className="space-y-2 rounded-lg border border-slate-700 p-3 text-xs"><TransactionLink hash={tx.hash} caseId={caseId} /><p>{formatEth(BigInt(tx.value))} ({tx.value} wei)</p><p>{tx.timestamp || 'Timestamp unavailable'}</p><p>Receipt: {tx.status}</p></div>)}</>}
    </aside>
  </div>;
}
